= Chicken Feet Web

画鸡脚前端

== 底层依赖

* nodejs 14.15.4
* ionic cli 6.16.3
* angular 12.1.1

== 准备

. git clone 到工作目录，如该目录是Linux上经Samba映射的一个目录
. 查看并使用 Dockerfile.cli 编译 ionic cli 基镜像
. 随便挂载一个地方启动基镜像，如 docker run -it --rm -w /root -v /root/ssd/hostpath/tmp:/root ionic-cli:6.16.3 sh
. 执行 npm config set registry https://registry.npm.taobao.org
. 执行 ionic start "chicken-feet-web" blank --type=angular --no-git
. 一切选择 no
. 退出容器，把chicken-feet-front里面的所有内容拷贝到工作目录后再清空
. 执行 docker run -it --rm -p 50000:50000 -w /root/chicken-feet-web -v /root/ssd/hostpath/samba/chicken-feet-web:/root/chicken-feet-web ionic-cli:6.16.3 sh
. 执行 ionic serve --external --port 50000 --no-open
. 此时 Windows 可以映射到工作目录，通过 IDE 进行开发，通过浏览器访问 http://<Linux IP>:50000 就能看到结果

== 上库

. gitlab新建同名工程
. git clone 工程，并把里面的.git复制到上述工程目录中，再删除git clone下来的工程
. 上述工程中git bash执行 git config user.name "root" && git config user.email "admin@example.com"
. git add . && git commit -m "new project" && git push

== cli

* 快速生成，ionic 实际调用的 angular 的 cli

.bat
[source,bat]
----
ionic generate page <name>
ionic generate service <dir/name>
----

* 编译

ionic build --engine=browser --prod --source-map

== 二维码

npm install --save qrcode

== Angular

=== in-memory-web-api

https://github.com/angular/in-memory-web-api

https://github.com/angular/angular/tree/master/packages/misc/angular-in-memory-web-api

npm install angular-in-memory-web-api --save

但是按上述 准备 里写的，docker方式，调用不到API

==== Config

.ts
[source,ts]
----
/**
 * Interface for InMemoryBackend configuration options
 */
export abstract class InMemoryBackendConfigArgs {
  /**
   * The base path to the api, e.g, 'api/'.
   * If not specified than `parseRequestUrl` assumes it is the first path segment in the request.
   */
  apiBase?: string;
  /**
   * false (default) if search match should be case insensitive
   */
  caseSensitiveSearch?: boolean;
  /**
   * false (default) put content directly inside the response body.
   * true: encapsulate content in a `data` property inside the response body, `{ data: ... }`.
   */
  dataEncapsulation?: boolean;
  /**
   * delay (in ms) to simulate latency
   */
  delay?: number;
  /**
   * false (default) should 204 when object-to-delete not found; true: 404
   */
  delete404?: boolean;
  /**
   * host for this service, e.g., 'localhost'
   */
  host?: string;
  /**
   * false (default) should pass unrecognized request URL through to original backend; true: 404
   */
  passThruUnknownUrl?: boolean;
  /**
   * true (default) should NOT return the item (204) after a POST. false: return the item (200).
   */
  post204?: boolean;
  /**
   * false (default) should NOT update existing item with POST. false: OK to update.
   */
  post409?: boolean;
  /**
   * true (default) should NOT return the item (204) after a POST. false: return the item (200).
   */
  put204?: boolean;
  /**
   * false (default) if item not found, create as new item; false: should 404.
   */
  put404?: boolean;
  /**
   * root path _before_ any API call, e.g., ''
   */
  rootPath?: string;
}
----

== Ionic

=== ion-list

如下代码结构时，有些设备list会出现与header有一条缝隙，所以有加样式padding-top-0

.html
[source,html]
----
<ion-header>
  ...
</ion-header>
<ion-content>
  <ion-list class="padding-top-0">
  ...
----
